import {SearchResult} from "../types/search-resultl";

export const DATA: SearchResult = {
  kind: "youtube#videoListResponse",
  etag: '"Fznwjl6JEQdo1MGvHOGaz_YanRU/Cmodw7c5XPTM8Yg3kMXelihxek4"',
  pageInfo: {
    totalResults: 10,
    resultsPerPage: 10,
  },
  items: [
    {
      kind: "youtube#video",
      etag: "Frh850VEayWbdnAiUWAp9BAKSfU",
      id: {videoId: "OvLWWvjoi8s"},
      snippet: {
        publishedAt: "2019-12-03T15:38:54Z",
        channelId: "UCg8ss4xW9jASrqWGP30jXiw",
        title:
          "React JS + TypeScript. Введение в Типизацию (+ React Router DOM)",
        description:
          "🔗Исходники тут: https://t.me/js_by_vladilen/98\nПодпишись на меня в Instagram: https://www.instagram.com/vladilen.minin/\nTelegram: https://t.me/js_by_vladilen \n\nПодписывайся на соц сети:\nVK: https://vk.com/vladilen.minin \nГруппа VK: https://vk.com/js_by_vladilen \n\n🔗  Мои Курсы:\nПродвинутый JavaScript: https://clc.to/senior \nVue 3: https://clc.am/vuejs3 \nAngular 9: https://clc.to/angular \nReact Native: https://clc.to/rnative \nReactJS: https://clc.to/react \nNodeJS: https://clc.to/nodejs \nMEAN: https://clc.to/fullstack \nJavaScript: https://clc.to/javascript\n\nReact JS + TypeScript. Введение в Типизацию (+ React Router DOM)\nReact + TypeScript\nВ видео показываю работу с типизацией в React на примере приложения\nТак же рассматриваю @types + React Router DOM\nПриятного просмотра)",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/OvLWWvjoi8s/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/OvLWWvjoi8s/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/OvLWWvjoi8s/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/OvLWWvjoi8s/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/OvLWWvjoi8s/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Владилен Минин",
        tags: [
          "владилен минин",
          "react",
          "reactjs",
          "typescript",
          "javascript",
          "js",
          "ts",
          "tsx",
          "jsx",
          "react ts",
          "ts react",
          "react typescript",
          "react typescript уроки",
          "уроки typescript",
          "react router",
          "react router dom",
          "уроки react",
          "уроки js",
        ],
        categoryId: "27",
        liveBroadcastContent: "none",
        localized: {
          title:
            "React JS + TypeScript. Введение в Типизацию (+ React Router DOM)",
          description:
            "🔗Исходники тут: https://t.me/js_by_vladilen/98\nПодпишись на меня в Instagram: https://www.instagram.com/vladilen.minin/\nTelegram: https://t.me/js_by_vladilen \n\nПодписывайся на соц сети:\nVK: https://vk.com/vladilen.minin \nГруппа VK: https://vk.com/js_by_vladilen \n\n🔗  Мои Курсы:\nПродвинутый JavaScript: https://clc.to/senior \nVue 3: https://clc.am/vuejs3 \nAngular 9: https://clc.to/angular \nReact Native: https://clc.to/rnative \nReactJS: https://clc.to/react \nNodeJS: https://clc.to/nodejs \nMEAN: https://clc.to/fullstack \nJavaScript: https://clc.to/javascript\n\nReact JS + TypeScript. Введение в Типизацию (+ React Router DOM)\nReact + TypeScript\nВ видео показываю работу с типизацией в React на примере приложения\nТак же рассматриваю @types + React Router DOM\nПриятного просмотра)",
        },
        defaultAudioLanguage: "ru",
      },
      statistics: {
        viewCount: "120224",
        likeCount: "4099",
        dislikeCount: "38",
        favoriteCount: "0",
        commentCount: "252",
      },
    },
    {
      kind: "youtube#video",
      etag: "8A8lTyoSMmkHmtOQq4WjPQDW9Ag",
      id: {
        videoId: "Z5iWr6Srsj8",
      },
      snippet: {
        publishedAt: "2019-09-05T14:00:05Z",
        channelId: "UC-8QAzbLcRglXeN_MY9blyw",
        title: "React Typescript Tutorial",
        description:
          "Learn how to start using Typescript in your React code. I go over props, hooks, and render props. \n\n#react #typescript\n\nSnippets: https://gist.github.com/benawad/1e9dd01994f78489306fbfd6f7b01cd3#file-snippets-typescriptreact-json\n\nCode: https://github.com/benawad/react-typescript-example\n\nFor more information on this checkout: https://github.com/typescript-cheatsheets/react-typescript-cheatsheet\n\n----\nCheckout my side projects:\n\nIf you're into cooking: https://www.mysaffronapp.com/\n\n----\nJoin the Discord:  https://discord.gg/Vehs99V\n\n----\nPatreon: https://www.patreon.com/benawad\n\n----\nFollow Me Online Here:\n\n\nTwitch: https://www.twitch.tv/benawad\nGitHub: https://github.com/benawad\nLinkedIn: https://www.linkedin.com/in/benawad/\nInstagram: http://instagram.com/benawad97\nTwitter: https://twitter.com/benawad\n#benawad\nTikTok: https://www.tiktok.com/@benawad",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/Z5iWr6Srsj8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/Z5iWr6Srsj8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/Z5iWr6Srsj8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/Z5iWr6Srsj8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/Z5iWr6Srsj8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Ben Awad",
        tags: ["React", "Typescript", "React Typescript Tutorial"],
        categoryId: "28",
        liveBroadcastContent: "none",
        localized: {
          title: "React Typescript Tutorial",
          description:
            "Learn how to start using Typescript in your React code. I go over props, hooks, and render props. \n\n#react #typescript\n\nSnippets: https://gist.github.com/benawad/1e9dd01994f78489306fbfd6f7b01cd3#file-snippets-typescriptreact-json\n\nCode: https://github.com/benawad/react-typescript-example\n\nFor more information on this checkout: https://github.com/typescript-cheatsheets/react-typescript-cheatsheet\n\n----\nCheckout my side projects:\n\nIf you're into cooking: https://www.mysaffronapp.com/\n\n----\nJoin the Discord:  https://discord.gg/Vehs99V\n\n----\nPatreon: https://www.patreon.com/benawad\n\n----\nFollow Me Online Here:\n\n\nTwitch: https://www.twitch.tv/benawad\nGitHub: https://github.com/benawad\nLinkedIn: https://www.linkedin.com/in/benawad/\nInstagram: http://instagram.com/benawad97\nTwitter: https://twitter.com/benawad\n#benawad\nTikTok: https://www.tiktok.com/@benawad",
        },
        defaultAudioLanguage: "en",
      },
      statistics: {
        viewCount: "329824",
        likeCount: "8918",
        dislikeCount: "91",
        favoriteCount: "0",
        commentCount: "330",
      },
    },
    {
      kind: "youtube#video",
      etag: "xqiyPd0GrCPyXulhgRcRPFJu9lg",
      id: {videoId: "xL-a5Tox7Qw"},
      snippet: {
        publishedAt: "2020-11-11T10:00:15Z",
        channelId: "UCE9ODjNIkOHrnSdkYWLfYhg",
        title: "TypeScript & React. Полный курс",
        description:
          '#YauhenK #webDev #TypeScript #React #ityoutubersru\n\nВсех приветствую в курсе «TypeScript & React».\nВ данном видеокурсе мы с вами рассмотрим связку библиотеки React и синтаксиса TypeScript. Из библиотеки мы разберём типизацию функциональных и классовых компонентов, событий и элементов, методов жизненного цикла, контекста и портала и конечно же хуки. А в дополнение рассмотрим типизацию React-роутера и Redux.\n\n✒ Репозиторий курса:\n✔ https://github.com/YauhenKavalchuk/typescript-react\n\n✒ Timeline:\n✔ 0:00 - Введение \n✔ 1:42 - Установка окружения\n✔ 7:21 - Типизация функциональных компонентов\n✔ 13:14 - Типизация классовых компоненты\n✔ 19:52 - Типизация событий\n✔ 26:53 - Типизация элементов\n✔ 33:12 - Типизация контекста и портала\n✔ 40:49 - Типизация Хуков\n✔ 46:33 - Типизация ХОК-ов\n✔ 50:31 - Типизация Роутера\n✔ 56:27 - Типизация асинхронных функций \n✔ 1:01:33 - Типизация Редакса. Часть 1\n✔ 1:07:37 - Типизация Редакса. Часть 2\n\n✒ Используемые ресурсы и инструменты:\n✔ Visual Studio Code (редактор кода): https://code.visualstudio.com\n✔ Create React App (рабочее окружение): https://github.com/facebook/create-react-app\n✔ Redux Devtools (расширение для браузера): https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=ru\n✔ Fake online REST API: https://jsonplaceholder.typicode.com/\n✔ Redux-LocalStorage-Simple: https://www.npmjs.com/package/redux-localstorage-simple\n\n✒ Полезные ссылки:\n✔ Description "tsconfig.json": https://gist.github.com/YauhenKavalchuk/69054ba65e7863226e531b74cb33f060\n✔ React Context: https://youtu.be/W_-TO_reSGs\n✔ React Portal: https://youtu.be/xcWaYD4gZAs\n✔ React Typescript Cheatsheet: https://github.com/typescript-cheatsheets/react-typescript-cheatsheet\n✔ TypeScript and React(stefan baumgartner): https://fettblog.eu/typescript-react/\n✔ TypeScript React Starter: https://github.com/Microsoft/TypeScript-React-Starter#typescript-react-starter\n✔ React Static Type Checking: https://reactjs.org/docs/static-type-checking.html\n\n✒ Полный список готовых и планируемых курсов:\n✔ Trello: https://trello.com/b/R6rD7qq8\n\n✒ Автор курса:\n✔ YouTube: https://www.youtube.com/YauhenKavalchuk\n✔ Instagram: https://www.instagram.com/YauhenKavalchuk\n✔ Twitter: https://twitter.com/YauhenKavalchuk\n✔ VK: https://vk.com/YauhenKavalchuk\n✔ LinkedIn: https://www.linkedin.com/in/YauhenKavalchuk\n✔ GitHub: https://github.com/YauhenKavalchuk\n✔ VK (Группа): http://vk.com/webdevcom\n\n✒ Поддержать развитие канала:\n✔ YouTube-спонсорство: https://www.youtube.com/channel/UCE9ODjNIkOHrnSdkYWLfYhg/join\n✔ Patreon: https://www.patreon.com/YauhenKavalchuk',
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/xL-a5Tox7Qw/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/xL-a5Tox7Qw/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/xL-a5Tox7Qw/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/xL-a5Tox7Qw/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/xL-a5Tox7Qw/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "webDev",
        tags: [
          "web",
          "develop",
          "front-end",
          "frontend",
          "веб",
          "разработка",
          "программирование",
          "typescript function type",
          "typescript types",
          "typescript decorators",
          "typescript type",
          "typescript в браузере",
          "typescript введение",
          "typescript уроки",
          "typescript tutorial",
          "typescript 2020",
          "typescript основы",
          "введение в typescript",
          "typescript для начинающих",
          "typescript за час",
          "typescript и react",
          "typescript и redux",
          "typescript и react hooks",
          "typescript и react hoc",
          "typescript и react router",
        ],
        categoryId: "27",
        liveBroadcastContent: "none",
        defaultLanguage: "ru",
        localized: {
          title: "TypeScript & React. Полный курс",
          description:
            '#YauhenK #webDev #TypeScript #React #ityoutubersru\n\nВсех приветствую в курсе «TypeScript & React».\nВ данном видеокурсе мы с вами рассмотрим связку библиотеки React и синтаксиса TypeScript. Из библиотеки мы разберём типизацию функциональных и классовых компонентов, событий и элементов, методов жизненного цикла, контекста и портала и конечно же хуки. А в дополнение рассмотрим типизацию React-роутера и Redux.\n\n✒ Репозиторий курса:\n✔ https://github.com/YauhenKavalchuk/typescript-react\n\n✒ Timeline:\n✔ 0:00 - Введение \n✔ 1:42 - Установка окружения\n✔ 7:21 - Типизация функциональных компонентов\n✔ 13:14 - Типизация классовых компоненты\n✔ 19:52 - Типизация событий\n✔ 26:53 - Типизация элементов\n✔ 33:12 - Типизация контекста и портала\n✔ 40:49 - Типизация Хуков\n✔ 46:33 - Типизация ХОК-ов\n✔ 50:31 - Типизация Роутера\n✔ 56:27 - Типизация асинхронных функций \n✔ 1:01:33 - Типизация Редакса. Часть 1\n✔ 1:07:37 - Типизация Редакса. Часть 2\n\n✒ Используемые ресурсы и инструменты:\n✔ Visual Studio Code (редактор кода): https://code.visualstudio.com\n✔ Create React App (рабочее окружение): https://github.com/facebook/create-react-app\n✔ Redux Devtools (расширение для браузера): https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=ru\n✔ Fake online REST API: https://jsonplaceholder.typicode.com/\n✔ Redux-LocalStorage-Simple: https://www.npmjs.com/package/redux-localstorage-simple\n\n✒ Полезные ссылки:\n✔ Description "tsconfig.json": https://gist.github.com/YauhenKavalchuk/69054ba65e7863226e531b74cb33f060\n✔ React Context: https://youtu.be/W_-TO_reSGs\n✔ React Portal: https://youtu.be/xcWaYD4gZAs\n✔ React Typescript Cheatsheet: https://github.com/typescript-cheatsheets/react-typescript-cheatsheet\n✔ TypeScript and React(stefan baumgartner): https://fettblog.eu/typescript-react/\n✔ TypeScript React Starter: https://github.com/Microsoft/TypeScript-React-Starter#typescript-react-starter\n✔ React Static Type Checking: https://reactjs.org/docs/static-type-checking.html\n\n✒ Полный список готовых и планируемых курсов:\n✔ Trello: https://trello.com/b/R6rD7qq8\n\n✒ Автор курса:\n✔ YouTube: https://www.youtube.com/YauhenKavalchuk\n✔ Instagram: https://www.instagram.com/YauhenKavalchuk\n✔ Twitter: https://twitter.com/YauhenKavalchuk\n✔ VK: https://vk.com/YauhenKavalchuk\n✔ LinkedIn: https://www.linkedin.com/in/YauhenKavalchuk\n✔ GitHub: https://github.com/YauhenKavalchuk\n✔ VK (Группа): http://vk.com/webdevcom\n\n✒ Поддержать развитие канала:\n✔ YouTube-спонсорство: https://www.youtube.com/channel/UCE9ODjNIkOHrnSdkYWLfYhg/join\n✔ Patreon: https://www.patreon.com/YauhenKavalchuk',
        },
        defaultAudioLanguage: "ru",
      },
      statistics: {
        viewCount: "19706",
        likeCount: "840",
        dislikeCount: "21",
        favoriteCount: "0",
        commentCount: "86",
      },
    },
    {
      kind: "youtube#video",
      etag: "4eI-OiK92YWli6tPmp0xYTHpGho",
      id: {videoId: "jrKcJxF0lAU"},
      snippet: {
        publishedAt: "2021-04-17T11:26:04Z",
        channelId: "UCyLNhHSiEVkVwPSFKxJAfSA",
        title: "React with TypeScript Crash Course - 2021",
        description:
          "This is a 1.25 hour crash course aimed to teach you the React with TypeScript in great detail. \n\nTimelines: \n 0:00   - What is TypeScript\n 7:20 - Create a TypeScript React App\n 10:55 - Handling State\n 24:45 - Handling Props\n 31:08 - Handling Functions\n 40:36 - Handling Events\n\n\nGithub Repo:\nhttps://github.com/harblaith7/React-With-TypeScript-Crash-Course\n\n ** TAGS ** \nReact TypeScript Interface Scalar Types\n ** TAGS **",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/jrKcJxF0lAU/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/jrKcJxF0lAU/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/jrKcJxF0lAU/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/jrKcJxF0lAU/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/jrKcJxF0lAU/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Laith Harb",
        categoryId: "27",
        liveBroadcastContent: "none",
        localized: {
          title: "React with TypeScript Crash Course - 2021",
          description:
            "This is a 1.25 hour crash course aimed to teach you the React with TypeScript in great detail. \n\nTimelines: \n 0:00   - What is TypeScript\n 7:20 - Create a TypeScript React App\n 10:55 - Handling State\n 24:45 - Handling Props\n 31:08 - Handling Functions\n 40:36 - Handling Events\n\n\nGithub Repo:\nhttps://github.com/harblaith7/React-With-TypeScript-Crash-Course\n\n ** TAGS ** \nReact TypeScript Interface Scalar Types\n ** TAGS **",
        },
      },
      statistics: {
        viewCount: "31500",
        likeCount: "1055",
        dislikeCount: "8",
        favoriteCount: "0",
        commentCount: "90",
      },
    },
    {
      kind: "youtube#video",
      etag: "c_XGO7G6JHmUpbqjY7EBgbtM_Zo",
      id: {
        videoId: "ydkQlJhodio",
      },
      snippet: {
        publishedAt: "2021-04-19T15:04:23Z",
        channelId: "UCsBjURrPoezykLs9EqgamOA",
        title: "How to use TypeScript with React... But should you?",
        description:
          "Learn how to setup React with TypeScript. Compare the pros and cons of using TypeScript in an React project. Learn more in the full course 👉 https://fireship.io/courses/react-next-firebase/\n\n#js #react #typescript\n\n🔗 Resources\n\nFull TypeScript Video https://youtu.be/ahCwqrYpIuM\nTS Docs https://www.typescriptlang.org/\nCreate React App with TS https://create-react-app.dev/docs/adding-typescript/\n\n🤓 Install the quiz app \n\niOS https://itunes.apple.com/us/app/fireship/id1462592372?mt=8\nAndroid https://play.google.com/store/apps/details?id=io.fireship.quizapp\n\n🔥 Get more with Fireship PRO \n\nUpgrade to Fireship PRO at https://fireship.io/pro\nUse code lORhwXd2 for 25% off your first payment. \n\nMy VS Code Theme\n\n- Atom One Dark \n- vscode-icons\n- Fira Code Font",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/ydkQlJhodio/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/ydkQlJhodio/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/ydkQlJhodio/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/ydkQlJhodio/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/ydkQlJhodio/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Fireship",
        tags: [
          "webdev",
          "app development",
          "lesson",
          "tutorial",
          "react",
          "typescript",
          "ts",
          "ts vs js",
          "js",
          "javascript",
          "pros cons",
          "comparison",
          "typescript react tutorial",
        ],
        categoryId: "28",
        liveBroadcastContent: "none",
        localized: {
          title: "How to use TypeScript with React... But should you?",
          description:
            "Learn how to setup React with TypeScript. Compare the pros and cons of using TypeScript in an React project. Learn more in the full course 👉 https://fireship.io/courses/react-next-firebase/\n\n#js #react #typescript\n\n🔗 Resources\n\nFull TypeScript Video https://youtu.be/ahCwqrYpIuM\nTS Docs https://www.typescriptlang.org/\nCreate React App with TS https://create-react-app.dev/docs/adding-typescript/\n\n🤓 Install the quiz app \n\niOS https://itunes.apple.com/us/app/fireship/id1462592372?mt=8\nAndroid https://play.google.com/store/apps/details?id=io.fireship.quizapp\n\n🔥 Get more with Fireship PRO \n\nUpgrade to Fireship PRO at https://fireship.io/pro\nUse code lORhwXd2 for 25% off your first payment. \n\nMy VS Code Theme\n\n- Atom One Dark \n- vscode-icons\n- Fira Code Font",
        },
        defaultAudioLanguage: "en",
      },
      statistics: {
        viewCount: "219883",
        likeCount: "11312",
        dislikeCount: "138",
        favoriteCount: "0",
        commentCount: "791",
      },
    },
    {
      kind: "youtube#video",
      etag: "N7T5ox1emd1q2Pgd1coAvVRNUC4",
      id: {videoId: "doVgFdc6Op4"},
      snippet: {
        publishedAt: "2020-02-09T13:39:55Z",
        channelId: "UCTW0FUhT0m-Bqg2trTbSs0g",
        title:
          "03 - React + TypeScript за 30 минут/ React JS - Путь Самурая 2.0",
        description:
          "Поддержать меня и получить доступ к дополнительному контенту можно вот здесь:\nhttps://www.patreon.com/itkamasutra\n\nДрузья, TypeScript сам по себе большой и местами сложноватый. Но! Инструментом этим можно использовать, сильно не углубляясь, но получая просто огромнейший профит от использования связки React+TypeScript.\n\nВ данном выпуске, котоырй получился слегка скомканным, я примерно рассказал о том, что нам нужно понимать в TypeScript, чтобы радоваться всему, что происходит в React+Redux! В будущих выпусках мы типизируем все reducer-ы, api, connect, компоненты, redux-form, хуки! \n\nМы будем идти медленно и поэтапно. Вам ВСЁ будет понятно, даже если в этом выпуске вы слегка поднапряглись и испугались! Это такой, скажем так, обзор с высоты на, что предстоит!\n\nВы красавчики, самураи! Я вами горжусь! Спасибо за поддержку! Летим в космос вместе!\n\nПоддержать  проект монеткой: https://social-network.samuraijs.com\nПлатное обучение в онлайн или оффлайн инкубаторе:\nhttps://it-incubator.by\nhttps://it-kamasutra.com\n\nА здесь бесплатная взаимопомощь:\nhttps://t.me/reactjs_samurai\n\n* Мы в соц. сетях:\nhttps://vk.com/itkamasutra\nhttps://instagram.com/itkamasutra\nhttps://telegram.me/itkamasutra\n\n* Мои личные VK и Insta:\nhttps://vk.com/d.kuzyuberdin\nhttps://www.instagram.com/it.kamasutra.dimych/\n\n#reactJS #typescript #практика #примеры #уроки #курс\n\nУдачи нам, друзья!",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/doVgFdc6Op4/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/doVgFdc6Op4/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/doVgFdc6Op4/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/doVgFdc6Op4/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/doVgFdc6Op4/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "IT-KAMASUTRA",
        tags: [
          "javascript",
          "программирование",
          "уроки",
          "с",
          "нуля",
          "обучение",
          "js",
          "react",
          "react js",
          "reactjs",
          "react курс",
          "react практика",
          "react пример",
          "redux",
          "курсы",
          "инкубатор",
          "минск",
          "online",
          "бесплатно",
          "typescript",
        ],
        categoryId: "27",
        liveBroadcastContent: "none",
        defaultLanguage: "ru",
        localized: {
          title:
            "03 - React + TypeScript за 30 минут/ React JS - Путь Самурая 2.0",
          description:
            "Поддержать меня и получить доступ к дополнительному контенту можно вот здесь:\nhttps://www.patreon.com/itkamasutra\n\nДрузья, TypeScript сам по себе большой и местами сложноватый. Но! Инструментом этим можно использовать, сильно не углубляясь, но получая просто огромнейший профит от использования связки React+TypeScript.\n\nВ данном выпуске, котоырй получился слегка скомканным, я примерно рассказал о том, что нам нужно понимать в TypeScript, чтобы радоваться всему, что происходит в React+Redux! В будущих выпусках мы типизируем все reducer-ы, api, connect, компоненты, redux-form, хуки! \n\nМы будем идти медленно и поэтапно. Вам ВСЁ будет понятно, даже если в этом выпуске вы слегка поднапряглись и испугались! Это такой, скажем так, обзор с высоты на, что предстоит!\n\nВы красавчики, самураи! Я вами горжусь! Спасибо за поддержку! Летим в космос вместе!\n\nПоддержать  проект монеткой: https://social-network.samuraijs.com\nПлатное обучение в онлайн или оффлайн инкубаторе:\nhttps://it-incubator.by\nhttps://it-kamasutra.com\n\nА здесь бесплатная взаимопомощь:\nhttps://t.me/reactjs_samurai\n\n* Мы в соц. сетях:\nhttps://vk.com/itkamasutra\nhttps://instagram.com/itkamasutra\nhttps://telegram.me/itkamasutra\n\n* Мои личные VK и Insta:\nhttps://vk.com/d.kuzyuberdin\nhttps://www.instagram.com/it.kamasutra.dimych/\n\n#reactJS #typescript #практика #примеры #уроки #курс\n\nУдачи нам, друзья!",
        },
        defaultAudioLanguage: "ru",
      },
      statistics: {
        viewCount: "43410",
        likeCount: "2390",
        dislikeCount: "28",
        favoriteCount: "0",
        commentCount: "242",
      },
    },
    {
      kind: "youtube#video",
      etag: "BhpRwr3XR8qDI3GyXUre6R8hl8U",
      id: {videoId: "92qcfeWxtnY"},
      snippet: {
        publishedAt: "2021-04-19T12:30:01Z",
        channelId: "UCDzGdB9TTgFm8jRXn1tBdoA",
        title:
          "React TypeScript ПОЛНЫЙ КУРС 2021. Props, Events, Router, Hooks, Requests.",
        description:
          "В этом ролике мы рассмотрим основным нюансы связанные с типизацией React Typescript. Уроки по React Typescript. Typescript react router dom. Typescript react props. Typescript React hooks. React ts\n\nВ продолжение к этому курсу смотреть:\nReact Redux Typescript - https://youtu.be/ETWABFYv0GM\nFullstack Разработка на TypeScript - https://youtu.be/A0CfYSVzAZI\n\n\nИсходный код - https://github.com/utimur/React-typescript-course\n\nТаймкоды:\n\n00:00 - Введение.\n02:10 - Разворачиваем приложение.\n03:10 - Первый компонент. Типизация пропсов. Interface CardProps\n06:00 - React.FunctionComponent. React.FC\n11:30 - Компонент UserList. IUser, IAddress\n16:35 - Компонент UserItem. \n17:55 - Типизация запроса axios. Типизация хука UseState()\n20:30 - Переиспользуемый компонент List. Generics, Обобщенные типы в typescript\n26:30 - Типизация событий. MouseEvents, DragEvents, ChangeEvents\n34:25 - Типизация хука useRef. Неуправляемый компонент\n36:00 - Типизация react-router-dom. UseHistory, useParams, BrowserRouter\n44:35 - Время ставить лайки и писать комментарии =))\n\n\nПоддержать меня и мой канал вы можете по ссылкам ниже.\nPatreon - https://www.patreon.com/ulbitv\n\nQiwi кошелек - http://qiwi.com/n/BODYE821\nЯндекс деньги - https://yoomoney.ru/to/4100116193037469\n\n#React #TypeScript #JavaScript",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/92qcfeWxtnY/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/92qcfeWxtnY/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/92qcfeWxtnY/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/92qcfeWxtnY/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/92qcfeWxtnY/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Ulbi TV",
        tags: [
          "React",
          "Typescript",
          "React Typescript",
          "React js уроки",
          "Typescript уроки",
          "React полный курс",
          "Typescript React уроки",
          "TypeScript для начинающих",
          "typescript react router",
          "Typescript react js",
          "typescript курс",
          "typescript 2021",
          "react 2021",
          "react typescript 2021",
          "typescript react hooks",
          "typescript react props",
          "typescript react events",
          "typescript react простым языком",
          "typescript react полный курс",
          "реакт тайпскрипт",
          "react ts",
          "ts",
          "реакт тс",
        ],
        categoryId: "28",
        liveBroadcastContent: "none",
        localized: {
          title:
            "React TypeScript ПОЛНЫЙ КУРС 2021. Props, Events, Router, Hooks, Requests.",
          description:
            "В этом ролике мы рассмотрим основным нюансы связанные с типизацией React Typescript. Уроки по React Typescript. Typescript react router dom. Typescript react props. Typescript React hooks. React ts\n\nВ продолжение к этому курсу смотреть:\nReact Redux Typescript - https://youtu.be/ETWABFYv0GM\nFullstack Разработка на TypeScript - https://youtu.be/A0CfYSVzAZI\n\n\nИсходный код - https://github.com/utimur/React-typescript-course\n\nТаймкоды:\n\n00:00 - Введение.\n02:10 - Разворачиваем приложение.\n03:10 - Первый компонент. Типизация пропсов. Interface CardProps\n06:00 - React.FunctionComponent. React.FC\n11:30 - Компонент UserList. IUser, IAddress\n16:35 - Компонент UserItem. \n17:55 - Типизация запроса axios. Типизация хука UseState()\n20:30 - Переиспользуемый компонент List. Generics, Обобщенные типы в typescript\n26:30 - Типизация событий. MouseEvents, DragEvents, ChangeEvents\n34:25 - Типизация хука useRef. Неуправляемый компонент\n36:00 - Типизация react-router-dom. UseHistory, useParams, BrowserRouter\n44:35 - Время ставить лайки и писать комментарии =))\n\n\nПоддержать меня и мой канал вы можете по ссылкам ниже.\nPatreon - https://www.patreon.com/ulbitv\n\nQiwi кошелек - http://qiwi.com/n/BODYE821\nЯндекс деньги - https://yoomoney.ru/to/4100116193037469\n\n#React #TypeScript #JavaScript",
        },
        defaultAudioLanguage: "ru",
      },
      statistics: {
        viewCount: "19870",
        likeCount: "1513",
        dislikeCount: "6",
        favoriteCount: "0",
        commentCount: "220",
      },
    },
    {
      kind: "youtube#video",
      etag: "MVxw0WKIUUDc8uWvtxwNz9NfeBo",
      id: {videoId: "F2JCjVSZlG0"},
      snippet: {
        publishedAt: "2020-07-09T14:14:13Z",
        channelId: "UC8butISFwT-Wl7EV0hUK0BQ",
        title: "React / Typescript Tutorial - Build a Quiz App",
        description:
          "Learn how to use React and TypeScript to create a quiz app project. You will also learn how to use Styled-Components with React.\n\n🔗 What you will make: https://tender-mcnulty-a4a646.netlify.app/\n💻 Code: https://github.com/weibenfalk/react-quiz\n\n🎥 Course from Thomas Weibenfalk. Check out his YouTube channel: https://www.youtube.com/user/Weibenfalk\n\n🔗 Thomas's website: https://www.weibenfalk.com/\n\n--\n\nLearn to code for free and get a developer job: https://www.freecodecamp.org\n\nRead hundreds of articles on programming: https://freecodecamp.org/news\n\nAnd subscribe for new videos on technology every day: https://youtube.com/subscription_center?add_user=freecodecamp",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/F2JCjVSZlG0/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/F2JCjVSZlG0/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/F2JCjVSZlG0/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/F2JCjVSZlG0/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/F2JCjVSZlG0/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "freeCodeCamp.org",
        tags: ["quizapp"],
        categoryId: "27",
        liveBroadcastContent: "none",
        localized: {
          title: "React / Typescript Tutorial - Build a Quiz App",
          description:
            "Learn how to use React and TypeScript to create a quiz app project. You will also learn how to use Styled-Components with React.\n\n🔗 What you will make: https://tender-mcnulty-a4a646.netlify.app/\n💻 Code: https://github.com/weibenfalk/react-quiz\n\n🎥 Course from Thomas Weibenfalk. Check out his YouTube channel: https://www.youtube.com/user/Weibenfalk\n\n🔗 Thomas's website: https://www.weibenfalk.com/\n\n--\n\nLearn to code for free and get a developer job: https://www.freecodecamp.org\n\nRead hundreds of articles on programming: https://freecodecamp.org/news\n\nAnd subscribe for new videos on technology every day: https://youtube.com/subscription_center?add_user=freecodecamp",
        },
      },
      statistics: {
        viewCount: "166382",
        likeCount: "4086",
        dislikeCount: "92",
        favoriteCount: "0",
        commentCount: "270",
      },
    },
    {
      kind: "youtube#video",
      etag: "q9glnd5ULC5-fiX_FTNpHg1ls-g",
      id: {videoId: "ETWABFYv0GM"},
      snippet: {
        publishedAt: "2021-02-06T10:00:08Z",
        channelId: "UCDzGdB9TTgFm8jRXn1tBdoA",
        title: "React & Redux & TypeScript ПОЛНЫЙ КУРС 2021",
        description:
          "В этом курсе мы на практике поработает с typescrit, react, redux и разработаем небольшое веб приложение.\n\nСсылка на исходный код - https://github.com/utimur/react-redux-typescript-course\n\nНеобходимые знания для прохождения этого курса здесь -----https://www.youtube.com/playlist?list=PL6DxKON1uLOHsBCJ_vVuvRsW84VnqmPp6\n\n\n↓↓↓ПЛЭЙЛИСТЫ ↓↓↓\n\nСобеседования - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOG0carDseYltoAovmnjjhZk\nПолные практические курсы - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOGtX2_vuBk-Z5Fzbm-DY0y1\nMobX & React - \nhttps://www.youtube.com/watch?v=jn-L1SFYdIc\nНаглядная теория - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOEPJFENF2fZ8LbQcgl9dUk0\nПолный курс по Redux -\nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOHsBCJ_vVuvRsW84VnqmPp6\nReact drag and drop - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOENy8yYgn0uLwB6p8eAW9NZ\nReact компоненты - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOGXDvAr_PFPwhdJLb6zYiKf\nReact + Redux + Webpack\nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOHTgN679Es1vkCS911i9HJX\nАнимации в React - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOH0vVpdrZhUAVpHerNbUxfF\nРазработка fullstack MERN web приложения -\nhttps://www.youtube.com/playlistlist=PL6DxKON1uLOGd4E6kG6d5K-tsTFj-Deln\n\nТаймкоды:\n00:00 -      Введение, теория, план на урок\n02:40 -      Инициализация Redux store\n03:20 -      Первый редюсер + типизация\n13:50 -      CombineReducer, Provider\n15:35 -      Создаем хук UseTypedSelector\n18:00 -      Ассинхронный action creator + типизация\n23:00 -      Создаем хук UseActions\n24:40 -      Второй редюсер, масштабируем приложение + постраничный вывод\n34:07 -      Расширяем useActions\n38:30 -      Не забываем лайки, комментарии, я старался =)\n\n\nПоддержать меня и мой канал вы можете по ссылкам ниже.\nQiwi кошелек - http://qiwi.com/n/BODYE821\nЯндекс деньги - https://yoomoney.ru/to/4100116193037469",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/ETWABFYv0GM/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/ETWABFYv0GM/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/ETWABFYv0GM/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/ETWABFYv0GM/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/ETWABFYv0GM/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Ulbi TV",
        tags: [
          "Redux",
          "react",
          "redux typescript",
          "react typescript",
          "react redux",
          "react redux ts",
          "ts",
          "redux ts",
          "ts react",
          "react redux typescript",
        ],
        categoryId: "28",
        liveBroadcastContent: "none",
        localized: {
          title: "React & Redux & TypeScript ПОЛНЫЙ КУРС 2021",
          description:
            "В этом курсе мы на практике поработает с typescrit, react, redux и разработаем небольшое веб приложение.\n\nСсылка на исходный код - https://github.com/utimur/react-redux-typescript-course\n\nНеобходимые знания для прохождения этого курса здесь -----https://www.youtube.com/playlist?list=PL6DxKON1uLOHsBCJ_vVuvRsW84VnqmPp6\n\n\n↓↓↓ПЛЭЙЛИСТЫ ↓↓↓\n\nСобеседования - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOG0carDseYltoAovmnjjhZk\nПолные практические курсы - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOGtX2_vuBk-Z5Fzbm-DY0y1\nMobX & React - \nhttps://www.youtube.com/watch?v=jn-L1SFYdIc\nНаглядная теория - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOEPJFENF2fZ8LbQcgl9dUk0\nПолный курс по Redux -\nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOHsBCJ_vVuvRsW84VnqmPp6\nReact drag and drop - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOENy8yYgn0uLwB6p8eAW9NZ\nReact компоненты - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOGXDvAr_PFPwhdJLb6zYiKf\nReact + Redux + Webpack\nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOHTgN679Es1vkCS911i9HJX\nАнимации в React - \nhttps://www.youtube.com/playlist?list=PL6DxKON1uLOH0vVpdrZhUAVpHerNbUxfF\nРазработка fullstack MERN web приложения -\nhttps://www.youtube.com/playlistlist=PL6DxKON1uLOGd4E6kG6d5K-tsTFj-Deln\n\nТаймкоды:\n00:00 -      Введение, теория, план на урок\n02:40 -      Инициализация Redux store\n03:20 -      Первый редюсер + типизация\n13:50 -      CombineReducer, Provider\n15:35 -      Создаем хук UseTypedSelector\n18:00 -      Ассинхронный action creator + типизация\n23:00 -      Создаем хук UseActions\n24:40 -      Второй редюсер, масштабируем приложение + постраничный вывод\n34:07 -      Расширяем useActions\n38:30 -      Не забываем лайки, комментарии, я старался =)\n\n\nПоддержать меня и мой канал вы можете по ссылкам ниже.\nQiwi кошелек - http://qiwi.com/n/BODYE821\nЯндекс деньги - https://yoomoney.ru/to/4100116193037469",
        },
        defaultAudioLanguage: "ru-Latn",
      },
      statistics: {
        viewCount: "24486",
        likeCount: "1367",
        dislikeCount: "6",
        favoriteCount: "0",
        commentCount: "301",
      },
    },
    {
      kind: "youtube#video",
      etag: "i3aO8LR2fo5R-_utBRJUEpHvFqA",
      id: {videoId: "z8lDwLKthr8"},
      snippet: {
        publishedAt: "2021-01-27T13:30:04Z",
        channelId: "UC6vRUjYqDuoUsYsku86Lrsw",
        title: "Typescript for React Components From Beginners to Masters",
        description:
          'Typescript is quickly becoming the industry standard for React development. Take your Typescript skills from beginner to masters level by learning everything you need to know about how to write components in React the right way.\n\nCheatsheet: https://github.com/typescript-cheatsheets/react\nCode: https://github.com/jherr/ts-hooks\n\nHope you folks enjoy this!    \n👉 If you enjoy this video, please like it and share it.    \n👉 Don\'t forget to subscribe to this channel for more updates: https://bit.ly/2E7drfJ\n👉 Weekly free newsletter: https://www.jackherrington.com/subscribe/\n👉 Discord server signup: https://discord.gg/ddMZFtTDa5\n\nIf you liked this video, buy me a coffee! https://www.buymeacoffee.com/bluecollarcoder\n\n💢 Watch our other videos:\n💟 Hacking your Github contribution graph: https://youtu.be/_ZQSPYDlk3U\n💟 Build a KK Slider Slider: https://youtu.be/2DbX0xFL0nk\n\nThank you for watching this video, click the "SUBSCRIBE" button for stay connected with this channel. \n\nSubscription Link:  https://bit.ly/2E7drfJ\n\n#reactjs #typescript',
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/z8lDwLKthr8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/z8lDwLKthr8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/z8lDwLKthr8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/z8lDwLKthr8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/z8lDwLKthr8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Jack Herrington",
        tags: [
          "react js",
          "react js tutorial",
          "learn react js",
          "react js project",
          "reactjs",
          "react js full course",
          "react js website",
          "react js crash course",
          "typescript",
          "react typescript",
          "react with typescript",
          "react hooks",
          "typescript components",
          "typescript react component",
          "beginner typescript projects",
          "react typescript component",
          "typescript cheatsheet",
          "typescript hooks",
          "typescript for react",
          "typescript for react components",
          "typescript and react",
          "typescript with react",
        ],
        categoryId: "28",
        liveBroadcastContent: "none",
        localized: {
          title: "Typescript for React Components From Beginners to Masters",
          description:
            'Typescript is quickly becoming the industry standard for React development. Take your Typescript skills from beginner to masters level by learning everything you need to know about how to write components in React the right way.\n\nCheatsheet: https://github.com/typescript-cheatsheets/react\nCode: https://github.com/jherr/ts-hooks\n\nHope you folks enjoy this!    \n👉 If you enjoy this video, please like it and share it.    \n👉 Don\'t forget to subscribe to this channel for more updates: https://bit.ly/2E7drfJ\n👉 Weekly free newsletter: https://www.jackherrington.com/subscribe/\n👉 Discord server signup: https://discord.gg/ddMZFtTDa5\n\nIf you liked this video, buy me a coffee! https://www.buymeacoffee.com/bluecollarcoder\n\n💢 Watch our other videos:\n💟 Hacking your Github contribution graph: https://youtu.be/_ZQSPYDlk3U\n💟 Build a KK Slider Slider: https://youtu.be/2DbX0xFL0nk\n\nThank you for watching this video, click the "SUBSCRIBE" button for stay connected with this channel. \n\nSubscription Link:  https://bit.ly/2E7drfJ\n\n#reactjs #typescript',
        },
        defaultAudioLanguage: "en",
      },
      statistics: {
        viewCount: "34850",
        likeCount: "1335",
        dislikeCount: "18",
        favoriteCount: "0",
        commentCount: "100",
      },
    },
    {
      kind: "youtube#video",
      etag: "Boe8wp7ZuSWabe1VLPyBzoSRlt8",
      id: {videoId: "sfmL6bGbiN8"},
      snippet: {
        publishedAt: "2021-01-21T14:26:24Z",
        channelId: "UC8butISFwT-Wl7EV0hUK0BQ",
        title: "Build a Shopping Cart with React and TypeScript - Tutorial",
        description:
          "Learn the fundamentals and how to build a ReactJS shopping cart with Typescript, Material UI, Styled Components and React-Query.\n\nThis tutorial uses a free open API for dummy data to the items in the shop. React-Query hooks is used for fetching the data from the API. \n\nStyled Components is used in combination with Material UI to customize the styles.\n\n💻 Code: https://github.com/weibenfalk/react-shopping-cart\n\n✏️ Course created by Thomas Weibenfalk. Check out his channel: https://www.youtube.com/channel/UCnnnWy4UTYN258FfVGeXBbg\n\n--\n\nLearn to code for free and get a developer job: https://www.freecodecamp.org\n\nRead hundreds of articles on programming: https://freecodecamp.org/news\n\nAnd subscribe for new videos on technology every day: https://youtube.com/subscription_center?add_user=freecodecamp",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/sfmL6bGbiN8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/sfmL6bGbiN8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/sfmL6bGbiN8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/sfmL6bGbiN8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/sfmL6bGbiN8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "freeCodeCamp.org",
        categoryId: "27",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title: "Build a Shopping Cart with React and TypeScript - Tutorial",
          description:
            "Learn the fundamentals and how to build a ReactJS shopping cart with Typescript, Material UI, Styled Components and React-Query.\n\nThis tutorial uses a free open API for dummy data to the items in the shop. React-Query hooks is used for fetching the data from the API. \n\nStyled Components is used in combination with Material UI to customize the styles.\n\n💻 Code: https://github.com/weibenfalk/react-shopping-cart\n\n✏️ Course created by Thomas Weibenfalk. Check out his channel: https://www.youtube.com/channel/UCnnnWy4UTYN258FfVGeXBbg\n\n--\n\nLearn to code for free and get a developer job: https://www.freecodecamp.org\n\nRead hundreds of articles on programming: https://freecodecamp.org/news\n\nAnd subscribe for new videos on technology every day: https://youtube.com/subscription_center?add_user=freecodecamp",
        },
        defaultAudioLanguage: "en",
      },
      statistics: {
        viewCount: "91709",
        likeCount: "2978",
        dislikeCount: "33",
        favoriteCount: "0",
        commentCount: "156",
      },
    },
    {
      kind: "youtube#video",
      etag: "YW9Ef9kTzDEz_6LPJ-xpWX5dfGQ",
      id: {videoId: "NjN00cM18Z4"},
      snippet: {
        publishedAt: "2017-08-31T19:25:02Z",
        channelId: "UCWv7vMbMWH4-V0ZXdmDpPBA",
        title:
          "TypeScript Tutorial - TypeScript for React - Learn TypeScript [2020]",
        description:
          "TypeScript Tutorial - TypeScript for React & Angular Developers.\n🚀Learn TypeScript for React and Angular apps. \n🔥Get the COMPLETE COURSE (60% OFF - LIMITED TIME): https://bit.ly/2WBl8kT\n\nWant to learn more from me? \n\nCourses: https://codewithmosh.com\nTwitter: https://twitter.com/moshhamedani\nFacebook: https://www.facebook.com/programmingwithmosh/\nBlog: http://programmingwithmosh.com\n\nLearn all about classes, objects, interfaces, properties, constructors and other essential object-oriented programming concepts in TypeScript. \n\nTABLE OF CONTENT \n\n00:41 What is TypeScript?\n03:04 Your First TypeScript Program\n06:03 Declaring Variables\n10:52 Types\n16:35 Type Assertions\n19:22 Arrow Functions\n21:05 Interfaces\n24:59 Classes\n29:29 Objects\n33:36 Constructors\n36:27 Access Modifiers\n39:23 Access Modifiers in Constructor Parameters\n41:04 Properties\n46:22 Modules\n\n#javascript #react",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/NjN00cM18Z4/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/NjN00cM18Z4/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/NjN00cM18Z4/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/NjN00cM18Z4/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/NjN00cM18Z4/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Programming with Mosh",
        tags: [
          "typescript tutorial",
          "typescript",
          "typescript tutorial for beginners",
          "typescript tutorial 2020",
          "typescript for beginners",
          "learn typescript",
          "typescript vs javascript",
          "typescript course",
          "learn typescript 2020",
          "typescript crash course",
          "typescript react",
          "typescript crash course 2020",
          "typescript nodejs",
          "typescript basics",
          "what is typescript",
          "angular",
          "web development",
          "mosh hamedani",
          "code with mosh",
          "programming with mosh",
          "ts",
          "react typescript",
          "typescript 2020",
          "react",
          "javascript",
          "react js",
        ],
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title:
            "TypeScript Tutorial - TypeScript for React - Learn TypeScript [2020]",
          description:
            "TypeScript Tutorial - TypeScript for React & Angular Developers.\n🚀Learn TypeScript for React and Angular apps. \n🔥Get the COMPLETE COURSE (60% OFF - LIMITED TIME): https://bit.ly/2WBl8kT\n\nWant to learn more from me? \n\nCourses: https://codewithmosh.com\nTwitter: https://twitter.com/moshhamedani\nFacebook: https://www.facebook.com/programmingwithmosh/\nBlog: http://programmingwithmosh.com\n\nLearn all about classes, objects, interfaces, properties, constructors and other essential object-oriented programming concepts in TypeScript. \n\nTABLE OF CONTENT \n\n00:41 What is TypeScript?\n03:04 Your First TypeScript Program\n06:03 Declaring Variables\n10:52 Types\n16:35 Type Assertions\n19:22 Arrow Functions\n21:05 Interfaces\n24:59 Classes\n29:29 Objects\n33:36 Constructors\n36:27 Access Modifiers\n39:23 Access Modifiers in Constructor Parameters\n41:04 Properties\n46:22 Modules\n\n#javascript #react",
        },
        defaultAudioLanguage: "en-US",
      },
      statistics: {
        viewCount: "408076",
        likeCount: "7847",
        dislikeCount: "316",
        favoriteCount: "0",
        commentCount: "357",
      },
    },
  ],
};
